org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
android.builtInKotlin=false
android.newDsl=false
